version: '3'

services:
  api:
    build: ./server
    volumes:
      - ./database:/home/database
    ports:
      - 5000:5000
  home:
    build: ./home
    volumes:
      - ./home-data:/config
    networks:
      - internal
    ports:
      - 8123:8123
  jupyter:
    build: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./server:/home/jovyan/work/server
      - ./database:/home/jovyan/work/database
      - ./jupyter-data:/home/jovyan/work/jupyter
    ports:
      - "8888:8888"
  sensor-mock:
    build: ./sensor-mock
    networks:
      - internal
    ports:
      - 9000:9000

networks:
  internal:
