version: '3'

services:
  api:
    build: ./server
    ports:
      - 5000:5000
  home:
    build: ./home
    volumes:
      - ./home-data:/config
    networks:
      - internal
    ports:
      - 8123:8123
  sensor-mock:
    build: ./sensor-mock
    networks:
      - internal
    ports:
      - 9000:9000

networks:
  internal:
