
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: localhost:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

sensor:
  - platform: rest
    name: ambient_sensors
    resource: http://sensor-mock:9000/sensor
    json_attributes:
      - temperature
      - humidity
      - illuminance
      - dust
      - noise
  - platform: template
    sensors:
      temperature:
        value_template: '{{ states.sensor.ambient_sensors.attributes["temperature"] }}'
        device_class: temperature
        unit_of_measurement: '°C'
      humidity:
        value_template: '{{ states.sensor.ambient_sensors.attributes["humidity"] }}'
        device_class: humidity
        unit_of_measurement: '%'
      illuminance:
        value_template: '{{ states.sensor.ambient_sensors.attributes["illuminance"] }}'
        device_class: illuminance
        unit_of_measurement: 'lx'
      dust:
        value_template: '{{ states.sensor.ambient_sensors.attributes["dust"] }}'
        unit_of_measurement: '%'
      noise:
        value_template: '{{ states.sensor.ambient_sensors.attributes["noise"] }}'
        unit_of_measurement: '%'
